# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# C:\projects\gmpy2-feedstock\recipe, last modified Mon Oct 15 09:44:56 2018
# ------------------------------------------------

package:
    name: gmpy2
    version: 2.0.8
source:
    patches:
        - 0001-Do-not-redefine-isnan-isinf.patch
        - 0002-PySlice_GetIndicesEx-is-a-macro.patch
    sha256: dd233e3288b90f21b0bb384bcc7a7e73557bb112ccf0032ad52aa614eb373d3f
    url: https://pypi.io/packages/source/g/gmpy2/gmpy2-2.0.8.zip
build:
    number: '1002'
    script:
        - python setup.py build_ext -f --shared=%LIBRARY_PREFIX% -DMSC_USE_DLL=1 install
    string: py37h7db29ea_1002
requirements:
    build:
        - vs2015_win-64 14.0.25123 h17c34da_3
    host:
        - mpc 1.1.0 h9e20aa4_1006
        - mpfr 4.0.1 vc14_0
        - mpir 3.0.0 vc14_0
        - python 3.7.0 hc182675_1005
        - vc 14 0
        - vs2015_runtime 14.0.25420 0
    run:
        - mpc >=1.1.0,<2.0a0
        - mpfr >=4.0.1,<5.0a0
        - mpir
        - python >=3.7,<3.8.0a0
        - vc 14.*
test:
    imports:
        - gmpy2
about:
    home: https://pypi.python.org/pypi/gmpy2
    license: LGPL 3
    license_file: COPYING.LESSER
    summary: GMP/MPIR, MPFR, and MPC interface to Python 2.6+ and 3.x
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
